### ISSUE TITLE
IDEA: Select multiple questions on the right to view correlation

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#10]
An idea for possible future implementation is to view multiple survey questions against each other. For example, I might want to see what people answered 'How familiar are you with the total quantity of water your / household uses each month?' compared with their answers to 'How is your lawn watered?' We could retain the categories of gender, education, or age with the colors and show a legend.

**Comment by mauriel133** [comment]
Wouldn't this be equivalent to allowing all survey questions to be used as categories for the Y-axis?

**Comment by AmberSJones** [comment]
Yes, we don't need to implement this. Closing.
