### ISSUE TITLE
Symbology to Emphasize Neutral Response

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#13]
On questions with a neutral/central/middle response (e.g., neither agree nor disagree), this category should be emphasized on the plot. Proposed idea is to shade the background gray.

**Comment by mauriel133** [comment]
I added a Red-to-Green gradient background to the columns for these kind of responses. The center value should appear in white.

**Comment by AmberSJones** [comment]
Great.
