### ISSUE TITLE
Additional Demographic Information

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#16]
Additional categories to be added to the demographic selection include:
-Originally from Utah
-Originally from this valley
-Farm Ties (do you or a relative currently farm)
-Survey site (Logan, Cedar City, etc.)
-Survey venue (store, museum, etc.)

**Comment by mauriel133** [comment]
Done

**Comment by AmberSJones** [comment]
I'm not seeing this on the sandbox server?

**Comment by mauriel133** [comment]
It should appear now. Notes:
-There is no data for "Originally from this valley" in the current survey data. 
-"Survey Site" is a collection of way too many unique zip codes to be used as a demographic selection option. This would require another type of visualization.

**Comment by AmberSJones** [comment]
Implementation looks great.

Regarding 'originally from this valley' and 'survey site', I think those may be implemented in the future.
