### ISSUE TITLE
Do not display text fields

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#18]
If there are any responses that are just text, they should all be lumped into an 'Other' category. These responses should be pre-processed before we receive them.

**Comment by AmberSJones** [comment]
Is this addressed? I don't think there are any examples of this anymore?

**Comment by mauriel133** [comment]
The zip code question is the only example, but we will address that with a map.

**Comment by AmberSJones** [comment]
Ok. I'm going to close this issue. If another example occurs, we need to ask the social scientists to address it in the codebook- i.e., pre-process it into categories.
