### ISSUE TITLE
Display more than one question at a time

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#19]
We need to implement the functionality to display responses to more than one question at a time. This would only be for related questions. For example, we would want to display the responses to Poor Water Quality, Flooding, and Water Shortages for the example below. Each of these should have a row of its own given that the x-axis responses are common. This would only be done at a overall level- we would need to disable the option of selecting the demographic distinction.
![image](https://cloud.githubusercontent.com/assets/5023186/5381027/89877540-805a-11e4-9167-63de35a604d9.png)

**Comment by AmberSJones** [comment]
Discussed on 1/22. Each question (e.g., Water shortages, Flooding, Poor water quality, etc.) should be made a check box. Clicking will trigger the check box. When multiple check boxes are selected, the demographics view is disabled. If just one check box is selected, the demographics view is enabled.

**Comment by AmberSJones** [comment]
Noticed some issues with this where the responses to a question are being incorrectly displayed.

**Comment by AmberSJones** [comment]
The (+) sign is great. Let's also implement a (-) sign so that questions can be easily removed from selection.

**Comment by AmberSJones** [comment]
Also need to address the header when multiple questions are selected- right now it shows up as the first selected question (in this example- Snow Sports) but it should probably be the overarching question category (in this example- Water Activity.)

**Comment by mauriel133** [comment]
The (-) buttons have been added.

**Comment by AmberSJones** [comment]
Excellent. Closing.
