### ISSUE TITLE
Add map for viewing zip codes

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#21]
At some point, we should add a map view to display the zip code responses. Use a map of Utah with zip code boundaries with markers in the middle or call-outs to denote the number of respondents in each zip code. 

If this gets implemented, I assume that Doug will get excited about the spatial view and want to add functionality to view responses to other questions tied to the zip codes.

**Comment by mauriel133** [comment]
I have implemented a simple google map that displays a marker for each zip code. When clicking or hovering the marker an info-window or a tooltip window will show up respectively.

The data for these markers is loaded and saved on the client the very first time the website is opened  and after that it will load instantly forever and ever.

**Comment by AmberSJones** [comment]
Looks good.
