### ISSUE TITLE
Elements for Each Survey

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#23]
We need to implement a date range for each survey, so let's have a BeginDate and an EndDate.

**Comment by horsburgh** [comment]
Let's remove the date.  For each survey, I want to see:

Title
Description
Link to Instrument PDF
Link to Survey Viewer
Link to About Survey Informational Page

**Comment by jcaraballo17** [comment]
What data is going to be on the About Survey Info Page?
Should I create a field in the database to store the content of that page?

**Comment by AmberSJones** [comment]
Look at issue #43

**Comment by jcaraballo17** [comment]
I added all the information on the database.

Here's what I came up with for displaying the information for the individual surveys on the homepage. What do you think?
![image](https://cloud.githubusercontent.com/assets/4700505/8090362/c6def874-0f6a-11e5-9199-f3387645a934.png)

**Comment by AmberSJones** [comment]
I like it. Let me know when you need content for each of those components.

**Comment by jcaraballo17** [comment]
Ok, just implemented all that. Mauriel will work on styling it the right way.
Right now we have a random pdf file and a couple of Lorem Ipsum paragraphs for the About Survey information, so anytime would be nice.

**Comment by mauriel133** [comment]
The page is now styled accordingly.

**Comment by AmberSJones** [comment]
Looks good! Closing.
