### ISSUE TITLE
Multiple Admin Accounts

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#24]
We need a way for people (other than @jcaraballo17 ) to be able to add surveys. This could be multiple users on the existing django admin site or we could consider an admin sign-in on the actual survey data viewer.

**Comment by horsburgh** [comment]
I'm not sure we want to do this one.  Let's discuss.

**Comment by jcaraballo17** [comment]
Created an admin account for each one of us in the production server.
