### ISSUE TITLE
Zip Code Map Viewer Option

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#25]
We need to develop the functionality for a zip code heat map type viewer. This would be a map of Utah with zip codes to which values would be assigned and the color should be scaled to the value. Maybe something like this: http://bl.ocks.org/mbostock/4060606

The view would only be available for certain questions. The values would be determined by the mean score for that question.

**Comment by mauriel133** [comment]
Amber, Jeff,

I'm implementing this feature right now. The example Amber shows above is good, but it is a representation of counties in the United States. The information we have for each respondent, however, is Venue and Zip Code.

A map representation for Zip Codes will look much more complex. Something like this: http://bl.ocks.org/jefffriesen/6892860

I could implement the counties map by getting the counties id from zip codes somehow. Should I make it a zip codes or counties representation?

**Comment by horsburgh** [comment]
We should use zip codes, but only for Utah.

**Comment by AmberSJones** [comment]
Yes, the example that I gave was just to show the type of map- for our case, the boundaries would be different. We want a zip codes representation, not counties.

That's great you found a zip code representation- we just need to crop it or zoom it to Utah only.

**Comment by mauriel133** [comment]
The map has been implemented.

**Comment by AmberSJones** [comment]
The map looks great. A few things: 
1. I'd like to rotate the map so that the shape of Utah is straight up and down.
2. We need a way to zoom in on the map.
3. We need to implement the map for the question 'what is your zip code?' Or maybe we just remove that question from display.

**Comment by mauriel133** [comment]
1. In progress
2. Done. We can now zoom in and out by clicking on a zip code area.
3. I don't understand this one very well. Let's discuss this on our next meeting.

**Comment by AmberSJones** [comment]
Just a reminder about these outstanding concerns with the map viewer.

**Comment by mauriel133** [comment]
The map now uses a different projection and does not appear rotated anymore.
New zooming and panning controls have been implemented.
- Zoom in and out with scroll wheel.
- Panning is done by clicking and dragging on the map.

**Comment by AmberSJones** [comment]
This is good. I could close the issue, but I wonder if we may still want to implement actual controls- like (+) and (-) buttons for zooming and a hand control for panning. Thoughts @horsburgh and @mauriel133 ?

**Comment by horsburgh** [comment]
It would be most intuitive if there was a small control that had a + and - button for zooming in and out.  Something like this:

![zoomcontrol](https://cloud.githubusercontent.com/assets/3485902/7823982/9594bd08-03bc-11e5-9312-0954870c55ac.png)

**Comment by mauriel133** [comment]
The buttons have been added.

**Comment by AmberSJones** [comment]
Great. Closing.
