### ISSUE TITLE
Mean Result View

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#27]
Requested is a view for the mean score response to a question. This would include error bars and would be based on scores falling in the midlines of each category box. This feature is lower priority than the others that we discussed on 4/8.

**Comment by horsburgh** [comment]
We could also implement this as a separate view if it clutters the existing view too much and if the category box midpoint issue is confusing.

**Comment by mauriel133** [comment]
@AmberSJones , @horsburgh ,
Could one of you draw me a graphical example of this feature so I can understand the idea?

**Comment by AmberSJones** [comment]
Yes, I'll take a stab at it.

**Comment by AmberSJones** [comment]
This is what I am envisioning for the mean score if implemented as a separate view. The mean score should be calculated for each row and displayed (This should be the same value that you are using to give values for the heat map). The small tick marks represent the error bars, though Doug needs to tell us the preferred method for calculation, so no need to implement yet. @horsburgh , feel free to weigh in.

![image](https://cloud.githubusercontent.com/assets/5023186/7349835/1ee54f84-ecb9-11e4-8b6c-2f770208e8d4.png)

**Comment by mauriel133** [comment]
Can we just hide 'Not sure' columns in this view?

**Comment by AmberSJones** [comment]
Yes, I think we can hide the 'Not Sure' column, though we might want to check with Doug and Courtney to see if there is a good way to represent it.

I do think the mean determination only works for interval-type questions, but as you mention, it's probably best to treat it as a feature for each question that is specified in the codebook.

**Comment by mauriel133** [comment]
Sounds good, I'll hide them from now. If we need them later I'll update the code.

**Comment by mauriel133** [comment]
Basic functionality (only mean value) for this feature is now ready for testing on sandbox. 

Do the tick bars next to the mean correspond to the margin of error for a sample proportion? If so, what confidence level should I use to calculate it?

**Comment by AmberSJones** [comment]
Yes, the tick marks on either side of the mean correspond to some margin of error or spread for the sample. I'll email Doug to see what measure we should use to determine it... I'm not sure if they would envision it as a standard deviation or a confidence interval or what.

I'm going to close this issue for now- the mean value view is well-implemented.
