### ISSUE TITLE
Issues with 'In What City Do You Live' 

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#3]
See the below screenshot. Many of the x-axis labels are 'No Response' and the rest are blank. These should all have separate categories.

![image](https://cloud.githubusercontent.com/assets/5023186/5049913/cb621ce6-6be6-11e4-9023-c033d661621e.png)

**Comment by mauriel133** [comment]
This error should not occur anymore, but there are still some issues wrapping x-axis labels. I will document this in another issue.
