### ISSUE TITLE
Demographic Variables are Selectable with Multiple Questions

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#32]
When multiple questions are selected using the + sign, the demographic categories can still be selected. These need to be disabled. Also, when this occurs, 'No Response' is displayed.

![image](https://cloud.githubusercontent.com/assets/5023186/7348184/a1dffeaa-ecac-11e4-992f-78b51f47e446.png)

**Comment by mauriel133** [comment]
The categories button is now disabled when using the multiple question selection feature.

**Comment by AmberSJones** [comment]
Great.
