### ISSUE TITLE
Question Facets Disappear

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#33]
I've been testing some of the new functionality- clicking around a lot, etc. There is now some strange behavior where the question facet panel disappears when the heat map or the mean view are being used. Screen shots below:
![image](https://cloud.githubusercontent.com/assets/5023186/7657361/9484734e-faee-11e4-9d29-4ab4124bebbd.png)
![image](https://cloud.githubusercontent.com/assets/5023186/7657368/a2702098-faee-11e4-8d9c-c0f859268aff.png)

**Comment by mauriel133** [comment]
I'm unable to reproduce this error. Could this have been an issue caused by an old cached page?

**Comment by AmberSJones** [comment]
Perhaps. I'll try to reproduce it.
