### ISSUE TITLE
Display of Questions Deactivated when Heat Map or Mean Viewer being used

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#35]
When the Heat Map or Mean Data View are active, the questions for which these views are not relevant disappear. I think we should keep them visible, but make them gray or muted to indicate that they cannot be selected for this type of view. Otherwise it seems like they just disappear- at first I thought it was a bug.

**Comment by mauriel133** [comment]
Done. Questions not available now appeared grayed out and display a not-allowed cursor on hover.

**Comment by AmberSJones** [comment]
Great.
