### ISSUE TITLE
Display text when hovering over buttons

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#37]
I think we should display some text when hovering over buttons to indicate the purpose- this will help users understand why they are unavailable at certain times. So, the text we would need is:
'Demographic Variables'
'Heat Map View'
'Mean Result View'
'Percentage View'

**Comment by mauriel133** [comment]
Added hover text for demographics dropdown list. The other ones were already added.

**Comment by AmberSJones** [comment]
Ok- I see them. It seems like too long before they display- is there any way to speed the response?

**Comment by horsburgh** [comment]
Works, but is slow. When mousing over you have to hover for too long.
