### ISSUE TITLE
Mean Data Viewer symbology

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#39]
Requested to make the color line thicker on this view. May also need to make the black indicator larger or thicker, too.

**Comment by mauriel133** [comment]
I already did. Is that still not enough?

**Comment by horsburgh** [comment]
I think it looks good.  But, you could probably still double the height of both the line and the mean marker.

**Comment by mauriel133** [comment]
Size has been doubled.

**Comment by AmberSJones** [comment]
Looks good to me. Closing.
