### ISSUE TITLE
Map Viewer Display Threshold

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#41]
We need to implement a minimum respondent threshold for displaying a zip code on the map viewer- it's not very meaningful to include one person. There is some statistical significance to using 5, so that should be the default. We will also need to add a place for this to be specified in the codebook template.

**Comment by mauriel133** [comment]
Fixed. The map is now initially sized to fit the screen.

**Comment by AmberSJones** [comment]
Great.
