### ISSUE TITLE
Add the Survey PDF

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#42]
We need to add a link to the survey PDF to the upper left corner as well as the Survey home page. We will get the PDF from Doug.

**Comment by mauriel133** [comment]
@jcaraballo17, we need another field in the database for these pdf files.

**Comment by mauriel133** [comment]
Survey has been linked. Currently using a sample pdf file.

**Comment by AmberSJones** [comment]
I'm sending you the pdf to add. Closing the issue.
