### ISSUE TITLE
Need to add an 'About Survey' Informational Page

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#43]
We need to add some text on the survey's methods, etc. This text will come from Doug (or whoever the surveyor is), and would be linked from the Surveys home page.

**Comment by mauriel133** [comment]
@jcaraballo17, we are going to need a field for these data in the database as well.

**Comment by mauriel133** [comment]
The page has been implemented. Now we need good content to put in it.

**Comment by AmberSJones** [comment]
Ok- I'm asking Doug for content. Closing the issue.
