### ISSUE TITLE
Implement Color Schema for Accessibility

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#44]
We need to implement a color schema that is appropriate for audiences that may have issues with color blindness, etc. There are guidelines for accessibility out there that we will need to research/reference.

**Comment by AmberSJones** [comment]
Ok, as much as I like our current color scheme, I think it could be improved for accessibility. On this page, I think we should choose the Blue-DarkRed, Blue-DarkOrange, or Blue-Orange: http://geog.uoregon.edu/datagraphics/color_scales.htm

@mauriel133 , they give 8 colors, you'll need to select just 5 for the bidirectional questions. For the unidimensional questions, we should just select one color (blue?) for the gradient.

See this page for a good example of how data mapped in these colors looks for common types of color blindness: http://geog.uoregon.edu/datagraphics/EOS/Light-and-Bartlein2005_fig1.pdf

**Comment by mauriel133** [comment]
For the unidimensional color scheme, Douglas mentioned in one of his emails that he wants red at the end of the scale.

> change color scheme for the items that have a unidimensional scale (concerns) and put red at the ‘most concerned’ end

**Comment by AmberSJones** [comment]
I would still vote for blue, but let's make it red or orange and see how it looks and what Doug thinks.

**Comment by mauriel133** [comment]
Done. Used Blue-to-Dark Red, 12 Steps for bidirectional questions and a scale of red for uni-dimensional questions.

**Comment by AmberSJones** [comment]
Seems good to me. I'm closing the issue.
