### ISSUE TITLE
Need to Implement Orientation/Instructions

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#45]
We need to implement some sort of orientation/instructions for users for the first time that they visit the site as some of the buttons/functions may not be obvious. This could be some sort of feature that animates the clicking of buttons, etc. It could also exist as a static page that could be referenced.

**Comment by AmberSJones** [comment]
If we do this one, we do it last because it is not key functionality.

**Comment by mauriel133** [comment]
I've implemented some simple orientations. I will need help coming up with better and more descriptive ones. I have also included a "Do not show again" checklist to opt out of these tips.

To re-enable these tips after opting out open your browser console and type the following command:
> localStorage.clear();

**Comment by AmberSJones** [comment]
Wow, looks really good! A few things to address including my suggestions for instructions text:

- [ ] On 1, change text to 'Select a question to visualize survey results. Use the '+' sign to view multiple questions simultaneously.
- [ ] On 2, change text to 'Use these buttons to toggle between different views for the selected question(s).'
- [ ] On 3, change text to 'Choose between predefined demographic categories to disaggregate data among groups of respondents.'
- [ ] Add a list of the three views to 2/3 with the thumbnail next to each:  
- Percentage View: Shows the number and percentage of respondents. Can be disaggregated into demographic groups.  
- Mean View: Shows the mean response for all respondents.  
- Heat Map View: Shows the mean response organized by the zip code of respondents.
- [ ] Add a 4 to give a tip on the statistical significance flag: 'For selected questions that show a matrix of responses, a flag is displayed to indicate the statistical significance of the results.'
- [ ] Change the 'Back' button to 'Previous'
- [ ] Need a space between the checkbox and 'Do Not Show Again'
- [ ] Could we add some images to show what each text box is explaining?

**Comment by mauriel133** [comment]
Yes, these are all great ideas. I think images would look great. I'll follow up with you on this idea.

**Comment by mauriel133** [comment]
Done. Let me know what you think.

**Comment by AmberSJones** [comment]
Sweet. I will wait to close until you demo at the meeting tomorrow.

**Comment by AmberSJones** [comment]
I just noticed that some of the text hasn't been updated to my suggestions on 1, 2, and 3.

Also, there are still issues with these when re-sizing.

**Comment by AmberSJones** [comment]
The colors on the orientation boxes help them to stand out, however, I think we should change them to be consistent with the colors on this pop-out box:
![image](https://cloud.githubusercontent.com/assets/5023186/8169050/441ed6b8-1364-11e5-93b0-b9d6d7e43bd6.png)

**Comment by mauriel133** [comment]
I changed the colors the other way around. Some of the properties in the style were required to show the little arrow in the orientation boxes. 

Let me know if this looks ok.

**Comment by AmberSJones** [comment]
I like the other way better, but this is probably fine. I'll close the issue.
