### ISSUE TITLE
Symbology Updates

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#46]
Requested to have:
-More saturated colors
-White Circles Filled in

**Comment by mauriel133** [comment]
Done. I could add more saturation to the colors. Let me know.

**Comment by AmberSJones** [comment]
The color saturation seems good. I think that it was desired to have a color other than white/gray/black for filling circles (one color for Yes, one color for No, etc), but we haven't determined which colors to use yet.
![image](https://cloud.githubusercontent.com/assets/5023186/7754608/353dff92-ffab-11e4-992f-f062a24aa08f.png)

**Comment by mauriel133** [comment]
Added colors for each column.

**Comment by AmberSJones** [comment]
Great. Closing.
