### ISSUE TITLE
Unidimensional Color Scheme

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#47]
We need to change the color scheme for the questions that are unidimensional (the Concerns). So, this should be a question type that we identify in the codebook and template. We could either:
1. Keep the current color scheme, but reverse it so that 'Very concerned' is red and 'not at all concerned' is green.
2. Use a single color with a gradient to white or gray. 'Very concerned' should be the solid color or most saturated level and 'Not at all concerned' should be white or gray.

**Comment by AmberSJones** [comment]
I think we need to do option 2.

**Comment by mauriel133** [comment]
Implemented option 2 with red gradient.

**Comment by AmberSJones** [comment]
This is great, but I'm concerned that there isn't enough difference in the gradient. Can we make the 0 more white and the 5 darker or more saturated?

![image](https://cloud.githubusercontent.com/assets/5023186/7973273/f9feaf10-0a10-11e5-8d59-0102c350b8ff.png)

**Comment by mauriel133** [comment]
I have implemented a new color scheme. Let me know what you think.

**Comment by AmberSJones** [comment]
I like it, but I don't think it will work for color blindness:
![image](https://cloud.githubusercontent.com/assets/5023186/7993681/19e90208-0ac5-11e5-9ef9-9aa72bfa6b15.png)

I think we should do the blue sequential scale shown on this page: http://geog.uoregon.edu/datagraphics/color_scales.htm
I just don't think it works well enough to do red for the color blindness issue.

**Comment by mauriel133** [comment]
Changed to the blue with 10 steps.

**Comment by AmberSJones** [comment]
Looks good. And my online color blind reference agrees:
![image](https://cloud.githubusercontent.com/assets/5023186/7994467/e5247f1a-0aca-11e5-9cf4-11d06e67b960.png)
