### ISSUE TITLE
Heat map base map when no question selected

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#48]
When no question is selected, the heat map should be colored to display the total number of respondents- maybe split into 5 groups.

**Comment by mauriel133** [comment]
How should these 5 groups be determined?

**Comment by AmberSJones** [comment]
Since we're doing a continuous scale for the map, it would be better not to split it into groups, but use the continuous scale with the maximum being the highest number of respondents in a zip code and the minimum being either 1 or 5 (since 5 is our cutoff for the questions).

**Comment by mauriel133** [comment]
Done.

**Comment by AmberSJones** [comment]
It looks great. This should also be displayed when the question 'Zip' is selected.

**Comment by mauriel133** [comment]
Done. Note that questions with the 'spatial' feature will only be available in the heat map view.

**Comment by AmberSJones** [comment]
Currently, the percentage view is still selectable with the zip code question selected.

**Comment by mauriel133** [comment]
Fixed.

**Comment by AmberSJones** [comment]
Excellent, closing. Way to knock these off this week!
