### ISSUE TITLE
About and Contact

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#53]
What did we determine to do for the About page? We need to remove the Contact page. Here's a first cut for the 'About' page. @mauriel133 and @horsburgh , feel free to add. I'm not sure if I want to spend time going into more detail or not...

The Survey Data Viewer is a web application for visualizing the results of social science survey data developed as part of the iUTAH Modeling and Data Federation (http://data.iutahepscor.org). For the code and additional documentation, see http://github.com/UCHIC/SurveyDataViewer. The code is may be adopted for general use following the stipulations in the code repository (https://github.com/UCHIC/SurveyDataViewer/blob/master/LICENSE). 

And then we should probably put this text and logos with links at the bottom of the page (same as on data.iutahepscor.org):
![image](https://cloud.githubusercontent.com/assets/5023186/8169522/5aff411c-1367-11e5-881d-70b0773f6b8c.png)

**Comment by horsburgh** [comment]
This is probably fine.  Note the grammatical issue:  "The code is may be" should be "The code may be"

**Comment by mauriel133** [comment]
Do we want this footer all over the website? Or how about everywhere except on the survey visualization page?

**Comment by AmberSJones** [comment]
I think everywhere except the survey visualization page.

**Comment by mauriel133** [comment]
Done.

**Comment by AmberSJones** [comment]
Great.
