### ISSUE TITLE
Change the minimum display threshold for the heat map

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#54]
We need to change the minimum threshold for zip code display on the heat map from 5 to 15 survey participants.

**Comment by mauriel133** [comment]
Threshold has been increased to 15. 

We should consider having this as a parameter in the codebook so that each survey can specify its own threshold.

**Comment by AmberSJones** [comment]
I think that's a good idea.

**Comment by AmberSJones** [comment]
I'm keeping this open so that we add this parameter to the codebook as you mentioned @mauriel133

**Comment by mauriel133** [comment]
The parameter has been implemented. It goes in the question with the "spatial" tag. It can be defined in the labels column (i.e: "threshold=5")

**Comment by AmberSJones** [comment]
Great, thanks. Closing.
