### ISSUE TITLE
Add an info icon for the statistical summary

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#55]
We need to add an info icon (some sort of lowercase i) next to the test for statistical significant to indicate that there is a link that provides additional information. This should either go to the right of the text or below the check mark icon. We need this done ASAP.

![image](https://cloud.githubusercontent.com/assets/5023186/14033507/801e06f6-f1e0-11e5-909f-4f9e4736a31f.png)

**Comment by AmberSJones** [comment]
Hey- this is great, but there is some issues with the text alignment- it goes outside of the box in which it should be confined. I'm trying to re-create some figures to get the paper re-submitted- can you address this soon?
![image](https://cloud.githubusercontent.com/assets/5023186/14738198/8d6b7398-083d-11e6-85eb-d0a325e1f8a0.png)

**Comment by jcaraballo17** [comment]
Test it now and let me know if any further changes are needed.

**Comment by horsburgh** [comment]
I can't seem to get it to happen anymore. @AmberSJones?

**Comment by AmberSJones** [comment]
Looks great. Closing.
