### ISSUE TITLE
Color Scale

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#62]
From Doug: The color scales on the variables used in the maps need to be tweaked to accentuate visual contrasts across the range of values we see in nearly all the zipcodes. As it is, there is almost no visual variation given that the mean values are mostly confined to a couple of the colors in the color ramp.  If we can provide more contrasting colors for different levels of the variables (and perhaps gradients for intermediate values between the categorical values), that would help make them more interesting. 

I'm not totally sure how to do this unless we go all the way to white/black on the extreme of the unidirectional scale. It might not be as much of an issue on the bidirectional scale.

See this screenshot for an example of what Doug is referring to:
![image](https://cloud.githubusercontent.com/assets/5023186/15404209/a1f755e8-1db9-11e6-97ac-353755ee4462.png)

**Comment by mauriel133** [comment]
After implementing the mean values in the popup window for each ZIP code we can observe that the range of values in some cases (including this one) is too small, therefore not producing much variation in color across the map. These colors, in this case, are correct and are the ones supposed to show to reflect such small variation in responses.

We can discuss this more, but I think it works as intended.

**Comment by AmberSJones** [comment]
Ok- I'm going to close it for now. Thanks for looking into this.
