### ISSUE TITLE
Demographic Variables with Many Categories

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#64]
We need to consider how to better represent demographic variables with many categories. One way is that we tell people to just aggregate the categories, but that is somewhat unsatisfying if we are claiming to support surveys generically. Some ideas:

 - Implement some functionality to aggregate categories within the viewer. We've talked about doing this before.
 - Change the viewer window so that it is scroll-able- not everything will fit on the page, but could still be view-able in one plot.

Others?

Here's an example:
![image](https://cloud.githubusercontent.com/assets/5023186/15404854/ad95f1e0-1dbc-11e6-829b-5dc4358d033a.png)

**Comment by AmberSJones** [comment]
We should set a maximum level for each row, and then implement scrolling if that level is exceeded.

**Comment by mauriel133** [comment]
Fix for this issue has been implemented and deployed to production. We went with a scroll-able window layout that triggers when the space is too small to distribute for each row.

**Comment by AmberSJones** [comment]
ok- this looks good for when scrolling is necessary. However, there are cases where the scrolling is triggered but it's really close to the threshold and I still might want to see it all on one screen. So, I zoom out to try to get it all on one screen. When I do this, there is some sort of frame that is smaller than the size of my window. Not sure if this makes sense- here's screenshot:

![image](https://cloud.githubusercontent.com/assets/5023186/16213474/df862878-370c-11e6-8129-c9f72c03e694.png)

**Comment by AmberSJones** [comment]
Decrease the scrolling threshold and address the white space when re-sizing.

**Comment by mauriel133** [comment]
I think I fixed the white space issue now. I also decreased the scrolling threshold. I have redeployed to production. Please confirm.

**Comment by AmberSJones** [comment]
This seems much improved. Closing.
