### ISSUE TITLE
Question title repeated

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#65]
The title of a question is repeated on both the black and white title lines when it should only be there once. The behavior is as expected for nested questions where the main title is on the black line and the subtitle is on the white line.
![image](https://cloud.githubusercontent.com/assets/5023186/16061669/7669ffc4-324b-11e6-96ff-285760d09366.png)

**Comment by mauriel133** [comment]
Fix has been pushed to production.
