### ISSUE TITLE
Multiple Response Question Type

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#66]
We need to rapidly implement support for question types that allow the user to select multiple responses (e.g., "select all that apply"). We need to:
- [x] Implement rules for encoding these in the data file (encode each response with a number, include multiple numbers for each respondent if appropriate separated by semi-colon)
- [x] Implement a new variable code to denote these questions (multiResponse?)
- [x] Implement visualization of these questions similar to the below sketch. Only percentage view will be implemented with these questions. Each circle will represent the percentage of the total that included that response. These can still be factored by demographic variables.

Did I miss anything @mauriel133 ?

![image](https://cloud.githubusercontent.com/assets/5023186/18330504/33ec2362-7516-11e6-8255-1db45ce336d3.png)

**Comment by mauriel133** [comment]
1 - The data will be encoded as semi-colon separated numbers which correspond to each selected option in the response (i.e: "2;3;5")
2 - The corresponding flag for this type of question is "multiResponse"
3 - Are we displaying the percentages even if they do not add to 100%?

**Comment by AmberSJones** [comment]
Yes- display the percentages (and the n values) even if they do not add to 100.

**Comment by AmberSJones** [comment]
I've included a multiResponse question on the 3Creeks survey data currently loaded to the viewer. It looks good, however, there is some weirdness (a blank line) with some demographic variables. The users are ready to go with the viewer- @mauriel133 , can you look into this as soon as possible?

![image](https://cloud.githubusercontent.com/assets/5023186/18788161/1cf03ed8-8163-11e6-9d5b-70383b98a528.png)

**Comment by mauriel133** [comment]
Fixed the issue above and deployed to production.

**Comment by Maurier** [comment]
This has been implemented
