### ISSUE TITLE
Make Axes Labels/Categories Sort-able

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#67]
We need to make the categories for the x and y axes sortable. They would sort based on the associated values from the codebook, so the sorting could only be done in two directions. The x axis would always be sortable and the y-axis would only be sortable when a demographic variable is selected. Implementation of this is high priority.

**Comment by mauriel133** [comment]
This feature has been implemented and deployed to production.

**Comment by AmberSJones** [comment]
I like it! Great implementation, @mauriel133 .
