### ISSUE TITLE
Group Results Button

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#70]
We've worked on this button lately- I think it's too wide. This could be quickly remedied by putting the words into two lines.

![image](https://cloud.githubusercontent.com/assets/5023186/20412262/cf5945a6-ace2-11e6-80ef-dce8207fcf55.png)

**Comment by Maurier** [comment]
This change has been implemented.

**Comment by AmberSJones** [comment]
Looks good.
