### ISSUE TITLE
View percentages in sub-categories

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/SurveyDataViewer#8]
We need to implement functionality to view percentages in sub-categories. Right now percentages are calculated based on the overall number of respondents. The new option would calculate based on the number of respondents in that category (e.g., within 60 and over, within 50-59, etc). We discussed implementing as a radio button or a dropdown selection at the top of the screen.

![image](https://cloud.githubusercontent.com/assets/5023186/5050423/677c1f88-6beb-11e4-90af-ca2e38f7dc16.png)

**Comment by mauriel133** [comment]
This is now the default behavior. Do we still need the option to calculate overall percentages?

**Comment by AmberSJones** [comment]
No, I don't think it's desired to have the overall percentage. Closing.
